"""empty message

Revision ID: af116e16b2a5
Revises: 333a18df8589
Create Date: 2022-08-13 16:29:48.496295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af116e16b2a5'
down_revision = '333a18df8589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('cover_img', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'cover_img')
    # ### end Alembic commands ###
